import { PublicKey } from "@solana/web3.js";

/// Program IDs for the kidney-owned mainnet-scope deploy on devnet.
/// Mirrors `.env.devnet.kidney.mainnet-scope` in the repo root —
/// regenerated by `scripts/ops/deploy-devnet.sh --fresh --mainnet-scope`.
///
/// Hardcoded here (not read from .env) because Vite refuses to import
/// dotenv files outside its `envDir`, and threading a build-time
/// rewrite through CI is more complexity than this demo needs. Update
/// these constants if the deploy authority rotates the keypairs.
///
/// Two deployments coexist on devnet:
///   - "Muse canonical" — the original deploy at the IDs hardcoded
///     across `DEVNET_TESTING.md` (Authority: 6t4B…, frozen since the
///     SetFee/SetCap work landed)
///   - "Kidney parallel" — fresh deploy by Authority: 6pZu…, this is
///     where the post-hardening binaries live and what the demo
///     points at by default.
export const NETWORK = "devnet" as const;

export const RPC_URL = "https://api.devnet.solana.com";

export interface ProgramRef {
  name: string;
  address: PublicKey;
  role: string;
  scope: "mainnet-v1" | "research" | "legacy";
}

export const PROGRAMS: ProgramRef[] = [
  {
    name: "axis-vault",
    address: new PublicKey("Agae3WetHx7J9CE7nP927ekzAeegSKE1KfkZDMYLDGHX"),
    role: "ETF lifecycle (Create / Deposit / Withdraw / Sweep / SetFee / SetCap)",
    scope: "mainnet-v1",
  },
  {
    name: "pfda-amm-3",
    address: new PublicKey("3SBbfZgzAHyaijxbUbxBLt89aX6Z2d4ptL5PH6pzMazV"),
    role: "3-token PFDA batch auction with Switchboard oracle + Jito bid",
    scope: "mainnet-v1",
  },
];
